// Compiles the exact production handler and service prologue generated by
// CafeF1Entry.ps1. Dependencies are inert counters; no UI or user-file access.
#include "../Library/CafeLock.h"
#include <iostream>

namespace { bool locked = true, f1Active = false, f1Revoked = false, f1Shutdown = false;
int entries = 0, inspections = 0, paths = 0;
HWND m_Window = reinterpret_cast<HWND>(1);
struct Tray { HWND GetWindow() { return m_Window; } } fixtureTray;
struct Runtime {
 Tray* GetTrayIcon() { return &fixtureTray; }
 std::wstring GetSkinPath() { ++paths; return L"inert-skins"; }
 std::wstring GetPath() { ++paths; return L"inert-program"; }
} runtime;
Runtime& GetRainmeter() { ++paths; return runtime; }
BOOL TestIsWindow(HWND window) { return window != nullptr; }
}
bool CafeLock::IsLocked() { return locked; }
namespace CafeShelf { namespace F1 {
int Inspect(const std::wstring&, const std::wstring&) { ++inspections; return 0; }
}}
#define IsWindow TestIsWindow
#include "CafeF1EntrySnippet.inc"
#undef IsWindow

int main()
{
 // A live handler receives its real command ID while authorization is revoked.
 DispatchF1Settings(118);
 if (entries || inspections || paths) { std::cerr << "FAIL locked Settings handler entered service\n"; return 1; }
 // Direct service invocation must stop before paths or inspection are entered.
 CafeLock::OpenShelfSuiteF1Compatibility(m_Window);
 if (entries != 1 || inspections || paths) { std::cerr << "FAIL locked service reached inspection\n"; return 1; }
 locked = false; entries = inspections = paths = 0;
 DispatchF1Settings(118);
 if (entries != 1 || inspections != 1 || paths == 0 || f1Active) { std::cerr << "FAIL authorized handler did not reach inspection\n"; return 1; }
 entries = inspections = paths = 0; f1Active = true;
 CafeLock::OpenShelfSuiteF1Compatibility(m_Window);
 if (entries != 1 || inspections || paths) { std::cerr << "FAIL reentrant service reached inspection\n"; return 1; }
 std::cout << "PASS compiled production F1 handler/service boundaries: locked entry denied before paths/inspection; authorized sanity; reentrancy\n";
 return 0;
}
